#
#   Makefile.fpc for Free Pascal Embedded RTL
#

[package]
main=rtl

[target]
loaders=$(LOADERS)


# not all targets include enough features to build all units so
# the common units which are not compiled for all CPUs are stored in
# CPU_SPECIFIC_COMMON_UNITS
units=$(SYSTEMUNIT) $(CPU_UNITS) $(UUCHARUNIT) $(OBJPASUNIT) $(ISO7185UNIT) $(EXTPASUNIT) $(HEAPMGRUNIT) $(CONSOLEIOUNIT) $(CPU_SPECIFIC_COMMON_UNITS) \
# $(MACPASUNIT) $(ISO7185UNIT) $(STRINGSUNIT)
       $(STRINGSUNIT) \
       $(SORTBASEUNIT) \
       $(DOSUNIT) \
       $(CTYPESUNIT) \
       $(CHARSETUNIT) $(CPALLUNIT) \
       $(SYSCONSTUNIT)
#implicitunits=exeinfo $(CP_UNITS)

#rsts=$(MATHUNIT) $(RTLCONSTSUNIT) $(TYPINFOUNIT) $(CLASSESUNIT) $(SYSCONSTUNIT)

[require]
nortl=y

[install]
fpcpackage=y

[default]
target=embedded

[compiler]
includedir=$(INC) $(PROCINC) $(ARCH)
sourcedir=$(INC) $(PROCINC) $(COMMON) $(ARCH)

[prerules]
RTL=..
INC=$(RTL)/inc
COMMON=$(RTL)/common
PROCINC=$(RTL)/$(CPU_TARGET)
UNITPREFIX=rtl
LOADERS=
ifeq ($(ARCH),mipsel)
ifeq ($(SUBARCH),pic32mx)
override LOADERS=startup
endif
endif

ifdef RELEASE
override FPCOPT+=-Ur
endif

CPU_UNITS=
SYSINIT_UNITS=
CPU_SPECIFIC_COMMON_UNITS=$(SYSUTILSUNIT) $(MATHUNIT) $(CLASSESUNIT) \
			  $(FGLUNIT) $(MACPASUNIT) $(TYPINFOUNIT) $(TYPESUNIT) \
			  $(RTLCONSTSUNIT) $(GETOPTSUNIT) $(LINEINFOUNIT) $(SOFTFPUUNIT)

# Sysutils special deps
SYSUTILS_DEPS_OS=$(HEAPMGRUNIT)$(PPUEXT)
# Dos unit, local source
DOSDIR=.
# Dos unit uses objfpc mode
DOS_DEPS_OS=$(OBJPASUNIT)$(PPUEXT)

ifeq ($(ARCH),aarch64)
CPU_SPECIFIC_COMMON_UNITS+=$(INTRINSICSUNIT)
CPU_UNITS=$(RASPI3UNIT) $(MMIOUNIT) $(MAILBOXUNIT) $(RASPIUARTUNIT) $(GPIOUNIT)
CPU_UNITS_DEFINED=1
endif

ifeq ($(ARCH),arm)
CPU_SPECIFIC_COMMON_UNITS+=$(INTRINSICSUNIT)
ifeq ($(SUBARCH),armv7m)
CPU_UNITS=$(LM3FURYUNIT) $(LM3TEMPESTUNIT) $(STM32F10X_LDUNIT) $(STM32F10X_MDUNIT) $(STM32F10X_HDUNIT) \
	$(STM32F10X_XLUNIT) $(STM32F10X_CONNUNIT) $(STM32F10X_CLUNIT) $(LPC13XXUNIT) $(LPC1768UNIT) \
	$(SAM3X8EUNIT) $(XMC4500UNIT) $(CORTEXM3UNIT) $(CORTEXM4UNIT) # thumb2_bare
CPU_UNITS_DEFINED=1
endif
ifeq ($(SUBARCH),armv7em)
CPU_UNITS=$(LM4F120UNIT) $(XMC4500UNIT) $(MK20D5UNIT) $(MK20D7UNIT) $(MK22F51212UNIT) $(MK64F12UNIT) \
	  $(STM32F401XXUNIT) $(STM32F407XXUNIT) $(STM32F411XEUNIT) $(STM32F429XXUNIT) $(STM32F446XXUNIT) \
	  $(STM32F745UNIT) $(STM32F746UNIT) $(STM32F756UNIT) $(NRF52UNIT) $(CORTEXM3UNIT) $(CORTEXM4UNIT) $(CORTEXM7UNIT) \
	  $(SAMD51P19AUNIT) # thumb2_bare
CPU_UNITS_DEFINED=1
endif
ifeq ($(SUBARCH),armv4t)
CPU_UNITS=$(LPC21X4UNIT) $(AT91SAM7X256UNIT) $(SC32442BUNIT)
CPU_UNITS_DEFINED=1
endif
ifeq ($(SUBARCH),armv4)
CPU_UNITS=$(LPC21X4UNIT) $(AT91SAM7X256UNIT) $(SC32442BUNIT)
CPU_UNITS_DEFINED=1
endif
ifeq ($(SUBARCH),armv6m)
CPU_UNITS=$(LPC8XXUNIT) $(LPC11XXUNIT) $(LPC122XUNIT) $(STM32F0XXUNIT) $(NRF51UNIT) $(CORTEXM0UNIT) $(RP2040UNIT)
CPU_UNITS_DEFINED=1
endif
ifeq ($(SUBARCH),armv7a)
CPU_UNITS=$(ALLWINNER_A20UNIT) $(RASPI2UNIT)
CPU_UNITS_DEFINED=1
endif
ifeq ($(CPU_UNITS_DEFINED),)
$(error No CPUs enabled for given SUBARCH, pass either a SUBARCH or set CPU_UNITS_DEFINED=1 if you know what you are doing)
endif
endif

ifeq ($(ARCH),i386)
CPU_UNITS=$(MULTIBOOTUNIT)
CPU_SPECIFIC_COMMON_UNITS+=$(INTRINSICSUNIT)
CPU_UNITS_DEFINED=1
ifeq ($(CPU_UNITS_DEFINED),)
$(error No CPUs enabled for given SUBARCH, pass either a SUBARCH or set CPU_UNITS_DEFINED=1 if you know what you are doing)
endif
endif

ifeq ($(ARCH),x86_64)
# CPU_UNITS=$(MULTIBOOTUNIT) $(INTRINSICSUNIT)
endif


ifeq ($(ARCH),mipsel)
ifeq ($(SUBARCH),pic32mx)
CPU_UNITS=pic32mx1xxfxxxb pic32mx2xxfxxxb pic32mx1xxfxxxc pic32mx2xxfxxxc pic32mx1xxfxxxd pic32mx2xxfxxxd pic32mx7x5fxxxl pic32mx7x5fxxxh
CPU_UNITS_DEFINED=1
endif
ifeq ($(CPU_UNITS_DEFINED),)
$(error No CPUs enabled for given SUBARCH, pass either a SUBARCH or set CPU_UNITS_DEFINED=1 if you know what you are doing)
endif
endif



ifeq ($(ARCH),wasm32)
CPU_SPECIFIC_COMMON_UNITS:=$(filter-out $(SOFTFPUUNIT), $(filter-out $(LINEINFOUNIT), $(CPU_SPECIFIC_COMMON_UNITS)))
endif

# Paths
OBJPASDIR=$(RTL)/objpas

[rules]
# .NOTPARALLEL:
# Get the system independent include file names.
# This will set the following variables :
# SYSINCNAMES
include $(INC)/makefile.inc
SYSINCDEPS=$(addprefix $(INC)/,$(SYSINCNAMES))

# Get the processor dependent include file names.
# This will set the following variables :
# CPUINCNAMES
include $(PROCINC)/makefile.cpu
SYSCPUDEPS=$(addprefix $(PROCINC)/,$(CPUINCNAMES))

# Put system unit dependencies together.
SYSDEPS=$(SYSINCDEPS) $(SYSCPUDEPS) $(INC)/softfpu.pp
override FPC_SYSTEM_OPT += @system.cfg

#
# Loaders
#

startup$(OEXT) : $(CPU_TARGET)/startup.s
        $(AS) $(ASTARGET) -o $(UNITTARGETDIRPREFIX)startup$(OEXT) $(CPU_TARGET)/startup.s  -mabi=32 -march=pic32mx -mtune=pic32mx -W -EL  -msym32

#
# Base Units (System, $(STRINGSUNIT), os-dependent-base-unit)
#

CONSOLEIO_DEPS= consoleio.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
        $(CONSOLEIO_DEPS_OS) $(CONSOLEIO_DEPS_CPU)

consoleio$(PPUEXT) : $(CONSOLEIO_DEPS)
        $(COMPILER) $(CONSOLEIO_OPT) $<

EmbeddedApi.ConsoleIO$(PPUEXT) : $(NSOSDIR)/EmbeddedApi.ConsoleIO.pp $(CONSOLEIO_DEPS)
	$(COMPILER) $(CONSOLEIO_OPT) -Fi. $<

HEAPMGR_DEPS= heapmgr.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
        $(HEAPMGR_DEPS_OS) $(HEAPMGR_DEPS_CPU)

heapmgr$(PPUEXT) : $(HEAPMGR_DEPS)
        $(COMPILER) $(HEAPMGR_OPT) $<

EmbeddedApi.HeapMGR$(PPUEXT) : $(NSOSDIR)/EmbeddedApi.HeapMGR.pp $(HEAPMGR_DEPS)
	$(COMPILER) $(HEAPMGR_OPT) -Fi. $<

#
# Unit specific rules
#

define CPU_UNITS_RULE
ifndef FPC_DOTTEDUNITS
$(1)$(PPUEXT): $(ARCH)/$(1).pp $(SYSTEMUNIT)$(PPUEXT) $(addsuffix $(PPUEXT),$(CPU_SPECIFIC_COMMON_UNITS))
else
$(eval UNIT_REG_NAME=$(subst EmbeddedApi.,,$(1)))
$(eval UNIT_REG_NAME=$(subst ARMApi.,,$(UNIT_REG_NAME)))
# mipsel is also not yet in namespaced
ifeq ($(ARCH),mipsel)
$(1)$(PPUEXT): $(ARCH)/$(1).pp $(SYSTEMUNIT)$(PPUEXT) $(addsuffix $(PPUEXT),$(CPU_SPECIFIC_COMMON_UNITS))
else
$(1)$(PPUEXT): $(NSOSDIR)/$(ARCH)/$(1).pp $(ARCH)/$(UNIT_REG_NAME).pp $(SYSTEMUNIT)$(PPUEXT) $(addsuffix $(PPUEXT),$(CPU_SPECIFIC_COMMON_UNITS))
endif
endif
endef
$(foreach unit,$(CPU_UNITS),$(eval $(call CPU_UNITS_RULE,$(unit))))

ifndef FPC_DOTTEDUNITS
$(addsuffix $(PPUEXT),$(CPU_UNITS)):
	$(COMPILER) -g $<
else
$(addsuffix $(PPUEXT),$(CPU_UNITS)):
	$(COMPILER) -g -Fi$(OSDIR) -Fi$(OSDIR)/$(ARCH) $<
endif

# i386 specific units


MULTIBOOT_DEPS = $(ARCH)/multiboot.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
        $(MULTIBOOT_DEPS_OS) $(MULTIBOOT_DEPS_CPU)

multiboot$(PPUEXT) : $(MULTIBOOT_DEPS)
        $(COMPILER) $(MULTIBOOT_OPT) $<

EmbeddedApi.multiboot$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.multiboot.pp $(MULTIBOOT_DEPS)
	$(COMPILER) $(MULTIBOOT_OPT) -Fi. -Fi$(ARCH) $<

# ARM specific units

#raspi2$(PPUEXT): $(ARCH)/raspi2.pp $(CONSOLEIOUNIT)$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
#	$(COMPILER) $(ARCH)/raspi2.pp

RASPI2_DEPS = $(ARCH)/raspi2.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
        $(RASPI2_DEPS_OS) $(RASPI2_DEPS_CPU)

raspi2$(PPUEXT) : $(RASPI2_DEPS)
        $(COMPILER) $(RASPI2_OPT) $<

EmbeddedApi.Raspi2$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.Raspi2.pp $(RASPI2_DEPS)
	$(COMPILER) $(RASPI2_OPT) -Fi. -Fi$(ARCH) $<

# AARCH64 specific units

# gpio unit
#
GPIO_DEPS = $(ARCH)/gpio.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
        $(GPIO_DEPS_OS) $(GPIO_DEPS_CPU)

gpio$(PPUEXT) : $(GPIO_DEPS)
        $(COMPILER) $(GPIO_OPT) $<

EmbeddedApi.gpio$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.gpio.pp $(GPIO_DEPS)
	$(COMPILER) $(GPIO_OPT) -Fi. -Fi$(ARCH) $<

#mmio$(PPUEXT): $(ARCH)/mmio.pp $(SYSTEMUNIT)$(PPUEXT)
#	$(COMPILER) $(ARCH)/mailbox.pp
MMIO_DEPS = $(ARCH)/mmio.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
        $(MMIO_DEPS_OS) $(MMIO_DEPS_CPU)

mmio$(PPUEXT) : $(MMIO_DEPS)
        $(COMPILER) $(MMIO_OPT) $<

EmbeddedApi.mmio$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.mmio.pp $(MMIO_DEPS)
	$(COMPILER) $(MMIO_OPT) -Fi. -Fi$(ARCH) $<

#mailbox$(PPUEXT): $(ARCH)/mailbox.pp mmio$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
#	$(COMPILER) $(ARCH)/mailbox.pp

MAILBOX_DEPS = $(ARCH)/mailbox.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) $(MMIOUNIT)$(PPUEXT) \
        $(MAILBOX_DEPS_OS) $(MAILBOX_DEPS_CPU)

mailbox$(PPUEXT) : $(MAILBOX_DEPS)
        $(COMPILER) $(MAILBOX_OPT) $<

EmbeddedApi.mailbox$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.mailbox.pp $(MAILBOX_DEPS)
	$(COMPILER) $(MAILBOX_OPT) -Fi. -Fi$(ARCH) $<

#raspiuart$(PPUEXT): $(ARCH)/raspiuart.pp mmio$(PPUEXT) mailbox$(PPUEXT) gpio$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
#	$(COMPILER) $(ARCH)/raspiuart.pp

RASPIUART_DEPS = $(ARCH)/raspiuart.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
	$(MAILBOXUNIT)$(PPUEXT) $(GPIOUNIT)$(PPUEXT) $(MMIOUNIT)$(PPUEXT) \
        $(RASPIUART_DEPS_OS) $(RASPIUART_DEPS_CPU)

raspiuart$(PPUEXT) : $(RASPIUART_DEPS)
        $(COMPILER) $(RASPIUART_OPT) $<

EmbeddedApi.raspiuart$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.raspiuart.pp $(RASPIUART_DEPS)
	$(COMPILER) $(RASPIUART_OPT) -Fi. -Fi$(ARCH) $<

#raspi3$(PPUEXT): $(ARCH)/raspi3.pp $(CONSOLEIOUNIT)$(PPUEXT) mmio$(PPUEXT) mailbox$(PPUEXT) raspiuart$(PPUEXT) gpio$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
#	$(COMPILER) $(ARCH)/raspi3.pp

RASPI3_DEPS = $(ARCH)/raspi3.pp $(SYSTEMUNIT)$(PPUEXT) $(OBJPASUNIT)$(PPUEXT) \
	$(CONSOLEIOUNIT)$(PPUEXT) $(MAILBOXUNIT)$(PPUEXT) $(GPIOUNIT)$(PPUEXT) \
	$(MMIOUNIT)$(PPUEXT) $(RASPIUARTUNIT)$(PPUEXT)  \
        $(RASPI3_DEPS_OS) $(RASPI3_DEPS_CPU)

raspi3$(PPUEXT) : $(RASPI3_DEPS)
        $(COMPILER) $(RASPI3_OPT) $<

EmbeddedApi.raspi3$(PPUEXT) : $(NSOSDIR)/$(ARCH)/EmbeddedApi.raspi3.pp $(RASPI3_DEPS)
	$(COMPILER) $(RASPI3_OPT) -Fi. -Fi$(ARCH) $<


