#
#   Makefile.fpc for Free Pascal Runtime Library
#

[package]
name=rtl
version=3.3.1

[target]
dirs_linux=linux
dirs_wince=wince
dirs_win64=win64
dirs_go32v1=go32v1
dirs_freebsd=freebsd
dirs_dragonfly=dragonfly
dirs_darwin=darwin
dirs_iphonesim=darwin
dirs_ios=darwin
dirs_haiku=haiku
dirs_netbsd=netbsd
dirs_openbsd=openbsd
dirs_macosclassic=macos
dirs_solaris=solaris
dirs_gba=gba
dirs_nds=nds
dirs_symbian=symbian
dirs_embedded=embedded
dirs_wii=wii
dirs_aix=aix
dirs_x86_64_android=android
dirs_arm_android=android
dirs_aarch64_android=android
dirs_mipsel_android=android
dirs_freertos=freertos
dirs_ps1=ps1

[install]
fpcpackage=y
createpackagefpc=y

[default]
fpcdir=..

[rules]
.NOTPARALLEL:
