#
#   Makefile.fpc for Free Pascal Runtime Library
#

[package]
name=rtl
version=3.3.1

[target]
dirs_linux=linux
dirs_win64=win64
dirs_go32v1=go32v1
dirs_darwin=darwin
dirs_iphonesim=darwin
dirs_ios=darwin
dirs_x86_64_android=android
dirs_aarch64_android=android
dirs_mipsel_android=android

[install]
fpcpackage=y
createpackagefpc=y

[default]
fpcdir=..

[rules]
.NOTPARALLEL:
