#
# Makefile.fpc for Free Pascal testing utilities
#

[install]
fpcpackage=y

[default]
fpcdir=../..

[require]
# We depend on the installed compiler with it's fpc.cfg
nortl=y

[target]
programs=dotest fptime fail testfail digest concat
programs_win32=prepup
programs_win64=prepup

[rules]
.NOTPARALLEL:

utils: all



digest$(SRCEXEEXT): digest.pp tsstring$(PPUEXT)
        $(COMPILER) $<

dotest$(SRCEXEEXT): dotest.pp bench$(PPUEXT) tsstring$(PPUEXT) redir$(PPUEXT) tsutils$(PPUEXT)
        $(COMPILER) $<

fptime$(SRCEXEEXT): fptime.pp bench$(PPUEXT)
        $(COMPILER) $<

testfail$(SRCEXEEXT): testfail.pp redir$(PPUEXT)
        $(COMPILER) $<
